name: pushing the images to ACR
on: push
jobs:
  acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: azure/docker-login@v2
        with: 
          login-server: qtdotnet.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Building the Docker Image
        run: docker build . -t qtdotnet.azurecr.io/dotnet:${{ github.run_id }}
      - name: Pushing the Images to ACR
        run: docker push qtdotnet.azurecr.io/dotnet:${{ github.run_id }}