name: Docker_Practice
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Docker Image Build
        run: docker build -t ${{ secrets.USERNAME }}/dotnet:${{ github.run_id }} .
      - name: Pushing the image to the DockerHub
        run: docker push ${{ secrets.USERNAME }}/dotnet:${{ github.run_id }}
      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.56.1            
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          skip-setup-trivy: true
  